name: Deploy to Server

on:
  push:
    branches:
      - master # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm docs:build

      - name: Deploy
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cd .vitepress/dist
          tar -czf project.tar.gz ./*
          scp -i ~/.ssh/deploy_key -P ${SERVER_PORT} project.tar.gz ${SERVER_USER}@${SERVER_HOST}:/tmp/
          ssh -i ~/.ssh/deploy_key -p ${SERVER_PORT} ${SERVER_USER}@${SERVER_HOST} "cd /www/wwwroot/code_docs && rm -rf * && tar -xzf /tmp/project.tar.gz && rm /tmp/project.tar.gz"
