name: Deploy to Server

on:
  push:
    branches:
      - master # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm docs:build

      - name: Upload build files
        run: |
          cd .vitepress/dist
          tar -czf /tmp/project.tar.gz .
          scp -P ${{ secrets.SERVER_PORT }} /tmp/project.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/project.tar.gz

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /www/wwwroot/code_docs
            rm -rf *
            tar -xzf /tmp/project.tar.gz
            rm /tmp/project.tar.gz
